package pojos.com;
// Generated 20/05/2016 09:28:53 PM by Hibernate Tools 4.3.1



/**
 * DireccionesId generated by hbm2java
 */
public class DireccionesId  implements java.io.Serializable {


     private int idDirecciones;
     private int personaIdPersona;

    public DireccionesId() {
    }

    public DireccionesId(int idDirecciones, int personaIdPersona) {
       this.idDirecciones = idDirecciones;
       this.personaIdPersona = personaIdPersona;
    }
   
    public int getIdDirecciones() {
        return this.idDirecciones;
    }
    
    public void setIdDirecciones(int idDirecciones) {
        this.idDirecciones = idDirecciones;
    }
    public int getPersonaIdPersona() {
        return this.personaIdPersona;
    }
    
    public void setPersonaIdPersona(int personaIdPersona) {
        this.personaIdPersona = personaIdPersona;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DireccionesId) ) return false;
		 DireccionesId castOther = ( DireccionesId ) other; 
         
		 return (this.getIdDirecciones()==castOther.getIdDirecciones())
 && (this.getPersonaIdPersona()==castOther.getPersonaIdPersona());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdDirecciones();
         result = 37 * result + this.getPersonaIdPersona();
         return result;
   }   


}


