package pojos.com;
// Generated 20/05/2016 09:28:53 PM by Hibernate Tools 4.3.1



/**
 * Direcciones generated by hbm2java
 */
public class Direcciones  implements java.io.Serializable {


     private DireccionesId id;
     private Persona persona;
     private String direccion;
     private boolean habilitado;

    public Direcciones() {
    }

	
    public Direcciones(DireccionesId id, Persona persona, boolean habilitado) {
        this.id = id;
        this.persona = persona;
        this.habilitado = habilitado;
    }
    public Direcciones(DireccionesId id, Persona persona, String direccion, boolean habilitado) {
       this.id = id;
       this.persona = persona;
       this.direccion = direccion;
       this.habilitado = habilitado;
    }
   
    public DireccionesId getId() {
        return this.id;
    }
    
    public void setId(DireccionesId id) {
        this.id = id;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public boolean isHabilitado() {
        return this.habilitado;
    }
    
    public void setHabilitado(boolean habilitado) {
        this.habilitado = habilitado;
    }




}


