package pojos.com;
// Generated 20/05/2016 09:28:53 PM by Hibernate Tools 4.3.1



/**
 * Telefonos generated by hbm2java
 */
public class Telefonos  implements java.io.Serializable {


     private TelefonosId id;
     private Persona persona;
     private String telefono;
     private String ubicacion;
     private boolean habilitado;

    public Telefonos() {
    }

	
    public Telefonos(TelefonosId id, Persona persona, boolean habilitado) {
        this.id = id;
        this.persona = persona;
        this.habilitado = habilitado;
    }
    public Telefonos(TelefonosId id, Persona persona, String telefono, String ubicacion, boolean habilitado) {
       this.id = id;
       this.persona = persona;
       this.telefono = telefono;
       this.ubicacion = ubicacion;
       this.habilitado = habilitado;
    }
   
    public TelefonosId getId() {
        return this.id;
    }
    
    public void setId(TelefonosId id) {
        this.id = id;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(String ubicacion) {
        this.ubicacion = ubicacion;
    }
    public boolean isHabilitado() {
        return this.habilitado;
    }
    
    public void setHabilitado(boolean habilitado) {
        this.habilitado = habilitado;
    }




}


