package pojos.com;
// Generated 20/05/2016 09:28:53 PM by Hibernate Tools 4.3.1



/**
 * TelefonosId generated by hbm2java
 */
public class TelefonosId  implements java.io.Serializable {


     private int idTelefonos;
     private int personaIdPersona;

    public TelefonosId() {
    }

    public TelefonosId(int idTelefonos, int personaIdPersona) {
       this.idTelefonos = idTelefonos;
       this.personaIdPersona = personaIdPersona;
    }
   
    public int getIdTelefonos() {
        return this.idTelefonos;
    }
    
    public void setIdTelefonos(int idTelefonos) {
        this.idTelefonos = idTelefonos;
    }
    public int getPersonaIdPersona() {
        return this.personaIdPersona;
    }
    
    public void setPersonaIdPersona(int personaIdPersona) {
        this.personaIdPersona = personaIdPersona;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TelefonosId) ) return false;
		 TelefonosId castOther = ( TelefonosId ) other; 
         
		 return (this.getIdTelefonos()==castOther.getIdTelefonos())
 && (this.getPersonaIdPersona()==castOther.getPersonaIdPersona());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdTelefonos();
         result = 37 * result + this.getPersonaIdPersona();
         return result;
   }   


}


